spring.application.name=spring-task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/project_manager
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=oleksandrparfesa
spring.datasource.password=password

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://localhost:8081/realms/task-manager/.well-known/openid-configuration